name: update

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日0点运行
  workflow_dispatch:

permissions: write-all

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests jinja2
      - name: Set search parameters
        run: |
          echo "SEARCH_QUERY=awesome in:name stars:>100" >> $GITHUB_ENV
          echo 'SEARCH_PARAMS={"q": "awesome in:name stars:>100", "sort": "stars", "order": "desc", "per_page": 100}' >> $GITHUB_ENV
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python update_readme.py
      - name: Deploy to GitHub Pages
        run: |
          cp index_template.html index.html
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md index.html
          git commit -m 'Auto update README and deploy to GitHub Pages'
          git push
          
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
